dist: trusty
sudo: false

matrix:
  fast_finish: true

language: python
# For a list of available versions, run
#     aws s3 ls s3://travis-python-archives/binaries/ubuntu/14.04/x86_64/
#
# Python 3.7+ needs a newer version of openssl than is available in trusty,
# so these must run on a newer platform (and since travis doesn't yet have
# containers for xenial, those must use VMs).
# YAML magic from https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-401924248
.mixins:
- &xenial-mixin
  dist: xenial
  sudo: true
  addons:
    apt:
      packages:
        - libgnutls-dev
jobs:
  include:
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - <<: *xenial-mixin
      python: "3.7"
    - <<: *xenial-mixin
      python: "nightly"

env:
  - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

install:
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y openjdk-8-jdk --no-install-recommends
  - pip install tox-travis

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi

script:
  - export BOTO_CONFIG=/dev/null  # https://github.com/travis-ci/travis-ci/issues/7940
  - tox
